package db.weibouser.dao;

import db.weibouser.entity.WeiBoUserData;
import db.weibouser.entity.WeiBoUserDataExample;
import java.sql.SQLException;
import java.util.List;

public interface WeiBoUserDataDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    void insert(WeiBoUserData record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    int updateByPrimaryKey(WeiBoUserData record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    int updateByPrimaryKeySelective(WeiBoUserData record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    List selectByExample(WeiBoUserDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    WeiBoUserData selectByPrimaryKey(String id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    int deleteByExample(WeiBoUserDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    int deleteByPrimaryKey(String id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    int countByExample(WeiBoUserDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    int updateByExampleSelective(WeiBoUserData record, WeiBoUserDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    int updateByExample(WeiBoUserData record, WeiBoUserDataExample example) throws SQLException;
}