package db.weibouser.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import db.weibouser.entity.WeiBoUserData;
import db.weibouser.entity.WeiBoUserDataExample;
import java.sql.SQLException;
import java.util.List;

public class WeiBoUserDataDAOImpl implements WeiBoUserDataDAO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    public WeiBoUserDataDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    public void insert(WeiBoUserData record) throws SQLException {
        sqlMapClient.insert("user_weibo.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    public int updateByPrimaryKey(WeiBoUserData record) throws SQLException {
        int rows = sqlMapClient.update("user_weibo.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    public int updateByPrimaryKeySelective(WeiBoUserData record) throws SQLException {
        int rows = sqlMapClient.update("user_weibo.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    public List selectByExample(WeiBoUserDataExample example) throws SQLException {
        List list = sqlMapClient.queryForList("user_weibo.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    public WeiBoUserData selectByPrimaryKey(String id) throws SQLException {
        WeiBoUserData key = new WeiBoUserData();
        key.setId(id);
        WeiBoUserData record = (WeiBoUserData) sqlMapClient.queryForObject("user_weibo.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    public int deleteByExample(WeiBoUserDataExample example) throws SQLException {
        int rows = sqlMapClient.delete("user_weibo.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    public int deleteByPrimaryKey(String id) throws SQLException {
        WeiBoUserData key = new WeiBoUserData();
        key.setId(id);
        int rows = sqlMapClient.delete("user_weibo.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    public int countByExample(WeiBoUserDataExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("user_weibo.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    public int updateByExampleSelective(WeiBoUserData record, WeiBoUserDataExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("user_weibo.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    public int updateByExample(WeiBoUserData record, WeiBoUserDataExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("user_weibo.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table user_weibo
     *
     * @abatorgenerated Wed Oct 25 17:51:14 CST 2017
     */
    private static class UpdateByExampleParms extends WeiBoUserDataExample {
        private Object record;

        public UpdateByExampleParms(Object record, WeiBoUserDataExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}