package db.qquser.entity;

public class QQUserData {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_qq.id
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_qq.regtime
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    private Long regtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_qq.logintime
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    private Long logintime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_qq.token
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    private String token;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_qq.id
     *
     * @return the value of user_qq.id
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_qq.id
     *
     * @param id the value for user_qq.id
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_qq.regtime
     *
     * @return the value of user_qq.regtime
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    public Long getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_qq.regtime
     *
     * @param regtime the value for user_qq.regtime
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    public void setRegtime(Long regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_qq.logintime
     *
     * @return the value of user_qq.logintime
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    public Long getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_qq.logintime
     *
     * @param logintime the value for user_qq.logintime
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    public void setLogintime(Long logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_qq.token
     *
     * @return the value of user_qq.token
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_qq.token
     *
     * @param token the value for user_qq.token
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    public void setToken(String token) {
        this.token = token;
    }
}