package db.user.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import db.user.entity.UserData;
import db.user.entity.UserDataExample;
import java.sql.SQLException;
import java.util.List;

public class UserDataDAOImpl implements UserDataDAO {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public UserDataDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public void insert(UserData record) throws SQLException {
		sqlMapClient.insert("user.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public int updateByPrimaryKey(UserData record) throws SQLException {
		int rows = sqlMapClient.update(
				"user.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public int updateByPrimaryKeySelective(UserData record) throws SQLException {
		int rows = sqlMapClient.update(
				"user.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public List selectByExample(UserDataExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"user.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public UserData selectByPrimaryKey(String user) throws SQLException {
		UserData key = new UserData();
		key.setUser(user);
		UserData record = (UserData) sqlMapClient.queryForObject(
				"user.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public int deleteByExample(UserDataExample example) throws SQLException {
		int rows = sqlMapClient.delete("user.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public int deleteByPrimaryKey(String user) throws SQLException {
		UserData key = new UserData();
		key.setUser(user);
		int rows = sqlMapClient.delete(
				"user.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public int countByExample(UserDataExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"user.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public int updateByExampleSelective(UserData record, UserDataExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"user.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public int updateByExample(UserData record, UserDataExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("user.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	private static class UpdateByExampleParms extends UserDataExample {
		private Object record;

		public UpdateByExampleParms(Object record, UserDataExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}