package db.user.dao;

import db.user.entity.UserData;
import db.user.entity.UserDataExample;
import java.sql.SQLException;
import java.util.List;

public interface UserDataDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	void insert(UserData record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	int updateByPrimaryKey(UserData record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	int updateByPrimaryKeySelective(UserData record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	List selectByExample(UserDataExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	UserData selectByPrimaryKey(String user) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	int deleteByExample(UserDataExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	int deleteByPrimaryKey(String user) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	int countByExample(UserDataExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	int updateByExampleSelective(UserData record, UserDataExample example)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	int updateByExample(UserData record, UserDataExample example)
			throws SQLException;
}