package db.teluser.entity;

public class TelUserData {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_tel.tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    private String tel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_tel.passwd
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    private String passwd;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_tel.regtime
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    private Long regtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_tel.logintime
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    private Long logintime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_tel.token
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    private String token;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_tel.tel
     *
     * @return the value of user_tel.tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_tel.tel
     *
     * @param tel the value for user_tel.tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_tel.passwd
     *
     * @return the value of user_tel.passwd
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_tel.passwd
     *
     * @param passwd the value for user_tel.passwd
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_tel.regtime
     *
     * @return the value of user_tel.regtime
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public Long getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_tel.regtime
     *
     * @param regtime the value for user_tel.regtime
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public void setRegtime(Long regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_tel.logintime
     *
     * @return the value of user_tel.logintime
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public Long getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_tel.logintime
     *
     * @param logintime the value for user_tel.logintime
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public void setLogintime(Long logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_tel.token
     *
     * @return the value of user_tel.token
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_tel.token
     *
     * @param token the value for user_tel.token
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public void setToken(String token) {
        this.token = token;
    }
}