package db.user.entity;

public class UserData {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column user.user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	private String user;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column user.passwd
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	private String passwd;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column user.logintime
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	private Long logintime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column user.regtime
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	private Long regtime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column user.token
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	private String token;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column user.user
	 * @return  the value of user.user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public String getUser() {
		return user;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column user.user
	 * @param user  the value for user.user
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public void setUser(String user) {
		this.user = user;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column user.passwd
	 * @return  the value of user.passwd
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public String getPasswd() {
		return passwd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column user.passwd
	 * @param passwd  the value for user.passwd
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column user.logintime
	 * @return  the value of user.logintime
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public Long getLogintime() {
		return logintime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column user.logintime
	 * @param logintime  the value for user.logintime
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public void setLogintime(Long logintime) {
		this.logintime = logintime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column user.regtime
	 * @return  the value of user.regtime
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public Long getRegtime() {
		return regtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column user.regtime
	 * @param regtime  the value for user.regtime
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public void setRegtime(Long regtime) {
		this.regtime = regtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column user.token
	 * @return  the value of user.token
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column user.token
	 * @param token  the value for user.token
	 * @abatorgenerated  Thu Oct 26 10:13:13 CST 2017
	 */
	public void setToken(String token) {
		this.token = token;
	}
}