package db.teluser.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import db.teluser.entity.TelUserData;
import db.teluser.entity.TelUserDataExample;
import java.sql.SQLException;
import java.util.List;

public class TelUserDataDAOImpl implements TelUserDataDAO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public TelUserDataDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public void insert(TelUserData record) throws SQLException {
        sqlMapClient.insert("user_tel.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public int updateByPrimaryKey(TelUserData record) throws SQLException {
        int rows = sqlMapClient.update("user_tel.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public int updateByPrimaryKeySelective(TelUserData record) throws SQLException {
        int rows = sqlMapClient.update("user_tel.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public List selectByExample(TelUserDataExample example) throws SQLException {
        List list = sqlMapClient.queryForList("user_tel.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public TelUserData selectByPrimaryKey(String tel) throws SQLException {
        TelUserData key = new TelUserData();
        key.setTel(tel);
        TelUserData record = (TelUserData) sqlMapClient.queryForObject("user_tel.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public int deleteByExample(TelUserDataExample example) throws SQLException {
        int rows = sqlMapClient.delete("user_tel.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public int deleteByPrimaryKey(String tel) throws SQLException {
        TelUserData key = new TelUserData();
        key.setTel(tel);
        int rows = sqlMapClient.delete("user_tel.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public int countByExample(TelUserDataExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("user_tel.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public int updateByExampleSelective(TelUserData record, TelUserDataExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("user_tel.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    public int updateByExample(TelUserData record, TelUserDataExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("user_tel.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    private static class UpdateByExampleParms extends TelUserDataExample {
        private Object record;

        public UpdateByExampleParms(Object record, TelUserDataExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}