package db.teluser.dao;

import db.teluser.entity.TelUserData;
import db.teluser.entity.TelUserDataExample;
import java.sql.SQLException;
import java.util.List;

public interface TelUserDataDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    void insert(TelUserData record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    int updateByPrimaryKey(TelUserData record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    int updateByPrimaryKeySelective(TelUserData record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    List selectByExample(TelUserDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    TelUserData selectByPrimaryKey(String tel) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    int deleteByExample(TelUserDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    int deleteByPrimaryKey(String tel) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    int countByExample(TelUserDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    int updateByExampleSelective(TelUserData record, TelUserDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_tel
     *
     * @abatorgenerated Wed Oct 25 17:50:18 CST 2017
     */
    int updateByExample(TelUserData record, TelUserDataExample example) throws SQLException;
}