package db.qquser.dao;

import db.qquser.entity.QQUserData;
import db.qquser.entity.QQUserDataExample;
import java.sql.SQLException;
import java.util.List;

public interface QQUserDataDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_qq
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    void insert(QQUserData record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_qq
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    int updateByPrimaryKey(QQUserData record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_qq
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    int updateByPrimaryKeySelective(QQUserData record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_qq
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    List selectByExample(QQUserDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_qq
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    QQUserData selectByPrimaryKey(String id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_qq
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    int deleteByExample(QQUserDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_qq
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    int deleteByPrimaryKey(String id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_qq
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    int countByExample(QQUserDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_qq
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    int updateByExampleSelective(QQUserData record, QQUserDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user_qq
     *
     * @abatorgenerated Wed Oct 25 17:50:42 CST 2017
     */
    int updateByExample(QQUserData record, QQUserDataExample example) throws SQLException;
}